spring:
  application:
    name: jir_backend
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  ai:
    ollama:
      base-url: ${AI_HOST}
      chat:
        options:
          model: gemma3


jwt:
  secret: "my_secret_long_long_long_long_long_long_long"
  expiration: 3600000

